### ISSUE TITLE
Error: Could not resolve module "glob"

### ISSUE THREAD

**Issue by alexsoin** [christian-beckmann/parcel-transformer-twig#2]
On startup it gives an error:

```
Build failed.

Error: Could not resolve module "glob" from "/home/name/parcel-test/node_modules/@christian-beckmann/parcel-transformer-twig/lib/index.js"

  Error: Could not resolve module "glob" from "/home/name/parcel-test/node_modules/@christian-beckmann/parcel-transformer-twig/lib/index.js"
  at $0578d0f6e116167e$export$fb2a0b866a8162dc.resolve (/home/name/parcel-test/node_modules/@parcel/package-manager/lib/index.js:5013:21)
  at NodePackageManager.resolveSync (/home/name/parcel-test/node_modules/@parcel/package-manager/lib/index.js:3512:42)
  at NodePackageManager.requireSync (/home/name/parcel-test/node_modules/@parcel/package-manager/lib/index.js:3353:34)
  at Module.m.require (/home/name/parcel-test/node_modules/@parcel/package-manager/lib/index.js:3367:25)
  at require (node:internal/modules/cjs/helpers:102:18)
  at Object.<anonymous> (/home/name/parcel-test/node_modules/@christian-beckmann/parcel-transformer-twig/lib/index.js:1:14)
  at Module._compile (node:internal/modules/cjs/loader:1105:14)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at NodePackageManager.load (/home/name/parcel-test/node_modules/@parcel/package-manager/lib/index.js:3376:15)

```

Launch script: `parcel src/*.twig`.

Project tree:

```
├── .parcelrc
├── .twigrc
├── package.json
└── src
    ├── app.js
    ├── base.twig
    ├── index.twig
    └── styles.css
```

package.json devDependencies:
```json
{
  ...
  "devDependencies": {
    "@christian-beckmann/parcel-transformer-twig": "github:christian-beckmann/parcel-transformer-twig",
    "parcel": "^2.5.0"
  }
}
```

**Comment by christian-beckmann** [comment]
@alexsoin 
Sry, for that. Updated the package.json 0.10
It has a conditional dependency, if you use watch, it uses "glob" package.

**Comment by alexsoin** [comment]
Yes, it helped, thanks! 

Please tell me, when includes files, an error occurs:

```
@parcel/transformer-html: Internal error: missing content
```

Layouts and partials are placed in folders:

![изображение](https://user-images.githubusercontent.com/3787132/167849232-c082593f-ad2b-4454-a8a9-dea96282f2f3.png)

I connect the `header.twig` to the `base.twig` as follows:

```twig
{% include "../partials/header.twig" %}
```

when connecting, you can not use relative paths or an error in another?

**Comment by christian-beckmann** [comment]
@alexsoin The plugin is using https://github.com/twigjs/twig.js/, maybe you find help there. 

PS: Did you tried "header.twig" directly?

**Comment by alexsoin** [comment]
I found that the problem is not in the include, when the project is built, all the included files are generated as separate html pages, although they are located in the views folder

![изображение](https://user-images.githubusercontent.com/3787132/167853986-2089d717-1f1c-4afd-9ab5-36f25a1e384f.png)

and if you include a file that contains links to other pages, then the following error occurs during assembly:

header.twg:

![изображение](https://user-images.githubusercontent.com/3787132/167854238-804907d1-ead3-46f1-82d0-aa5b2046cc76.png)

```
Build failed.

@parcel/core: Failed to resolve '/test.html' from './src/index.twig'

@parcel/resolver-default: Cannot load file '../test.html' in './src'.
💡 Did you mean '../dist/test.html'?
💡 Did you mean './test.twig'?
```

**Comment by alexsoin** [comment]
figured out the error, instead of `test.html` you need to specify `test.twig`. And that's why the extra html is generated incomprehensibly
